# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  projectName: Razor.SweetAlert2.Guide.Server

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.0.100-preview6-012264


- task: DotNetCoreCLI@2
  displayName: 'Building $(buildConfiguration)...'
  inputs:
    command: 'build'
    projects: '**/$(projectName).csproj'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publishing $(buildConfiguration)...'
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    projects: '**/$(projectName).csproj'
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'BuildOutput'
    publishLocation: 'Container'

#- task: Docker@2
#  inputs:
#    containerRegistry: 'basaingeal-docker-hub'
#    repository: 'razor-sweetalert2-guide'
#    command: 'buildAndPush'
#    Dockerfile: '**/Dockerfile'



